package com.osama.weather.update.model

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * The exact shape of version.json, regenerated by CI on every push (see
 * .github/workflows/build-release.yml). The app polls [com.osama.weather.util.UpdateConfig.VERSION_MANIFEST_URL]
 * for this file every time it starts.
 */
@Serializable
data class VersionInfo(
    @SerialName("version_code") val versionCode: Int,
    @SerialName("version_name") val versionName: String,
    @SerialName("apk_url") val apkUrl: String,
    @SerialName("force_update") val forceUpdate: Boolean = true,
    @SerialName("release_notes") val releaseNotes: String? = null,
    @SerialName("published_at") val publishedAt: String? = null
)

sealed interface UpdateCheckResult {
    data object UpToDate : UpdateCheckResult
    data class UpdateAvailable(val info: VersionInfo) : UpdateCheckResult
    data class Error(val message: String) : UpdateCheckResult
}
