package com.osama.weather.util

/**
 * Central place for every URL and tunable constant in the app.
 *
 * The only thing you *must* edit before shipping is [UpdateConfig.REPO_OWNER]
 * and [UpdateConfig.REPO_NAME] — everything else already points at the real,
 * public, keyless Open-Meteo endpoints described in the project brief.
 */
object ApiConfig {

    /** Weather forecast API — current + hourly + daily + 15-minute nowcast. */
    const val FORECAST_BASE_URL = "https://api.open-meteo.com/v1/forecast"

    /** Air quality API — pollutants + European & US AQI, hourly, 7-day. */
    const val AIR_QUALITY_BASE_URL = "https://air-quality-api.open-meteo.com/v1/air-quality"

    /** Geocoding API (also by Open-Meteo) — smart city/place search + localized names. */
    const val GEOCODING_BASE_URL = "https://geocoding-api.open-meteo.com/v1/search"

    /** How many days of daily + hourly forecast to request. Open-Meteo supports up to 16. */
    const val FORECAST_DAYS = 16

    /** How many 15-minute steps to request for the short-term precipitation nowcast (24h). */
    const val MINUTELY_15_STEPS = 96

    /** How many days of hourly air-quality forecast to request. */
    const val AIR_QUALITY_FORECAST_DAYS = 7

    /** Network timeouts, in seconds. */
    const val CONNECT_TIMEOUT_SECONDS = 15L
    const val READ_TIMEOUT_SECONDS = 20L
}

/**
 * Configuration for the self-hosted GitHub-Releases update channel described
 * in the project's update-system brief.
 *
 * ┌─────────────────────────────────────────────────────────────────────┐
 * │  REQUIRED ONE-TIME EDIT BEFORE YOUR FIRST RELEASE                    │
 * │  Replace REPO_OWNER / REPO_NAME with your actual GitHub username     │
 * │  and repository name (the CI workflow always publishes a release     │
 * │  tagged "latest", so these two URLs never need to change again).     │
 * └─────────────────────────────────────────────────────────────────────┘
 */
object UpdateConfig {
    const val REPO_OWNER = "ossamasal2012"
    const val REPO_NAME = "weather"

    private const val RELEASE_TAG = "latest"
    private const val RELEASE_BASE =
        "https://github.com/$REPO_OWNER/$REPO_NAME/releases/download/$RELEASE_TAG"

    /** The manifest the app polls on every cold start. Regenerated by CI on every push. */
    const val VERSION_MANIFEST_URL = "$RELEASE_BASE/version.json"

    /** Fallback used only if version.json doesn't carry its own apk_url field. */
    const val APK_DOWNLOAD_URL = "$RELEASE_BASE/app-release.apk"

    const val DOWNLOADED_APK_FILENAME = "al-taqs-weather-update.apk"
}
